# Generated by Django 3.1.6 on 2021-02-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('picture', models.ImageField(upload_to='hero_pictures', verbose_name='Imagem')),
                ('description', models.TextField(max_length=240, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Herói',
            },
        ),
    ]
