# Generated by Django 3.1.6 on 2021-02-04 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_hero_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='favorite',
        ),
        migrations.AddField(
            model_name='hero',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_heroes', to=settings.AUTH_USER_MODEL),
        ),
    ]
