# Generated by Django 3.1.6 on 2021-02-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210204_0248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='favorited_by',
        ),
    ]
