# Generated by Django 3.1.6 on 2021-02-04 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favoriteheroesperuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteheroesperuser',
            options={'verbose_name': 'Herói favorito por usuário', 'verbose_name_plural': 'Heróis favoritos por usuário'},
        ),
    ]
