# Generated by Django 3.1.6 on 2021-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210204_0313'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriteheroesperuser',
            constraint=models.UniqueConstraint(fields=('hero', 'user'), name='hero_object_unique_for_user'),
        ),
    ]
